django_app/ARTICLE_SUMMARY2/ARTICLE_SUMMARY2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('', lambda request : redirect('board/', permanent=False)), # permanent = True로 설정하면 영구적 인 리디렉션이 발행됩니다.
    path('accounts/', include('accounts.urls')),
]

django_app/ARTICLE_SUMMARY2/accounts/urls.py
from django.urls import path, include
from django.shortcuts import redirect
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

django_app/ARTICLE_SUMMARY2/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('crawl/', views.text_summarizae_request_ajax, name='text_summarizae_request_ajax'),
    path('summarize/', views.news_summarizae_request_ajax, name='news_summarizae_request_ajax'),
    path('comments/', views.news_comments_request_ajax, name='news_comments_request_ajax'),
    path('history/', views.history_request_ajax, name='history_request_ajax'),
    
    # path('summarize/', views.summarize, name='summarize'),
]

django_app/ARTICLE_SUMMARY2/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, date_of_birth, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):

    class Meta:
        db_table = 'myuser'


    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

django_app/ARTICLE_SUMMARY2/accounts/forms.py
from django import forms
from django.contrib import admin
from django.contrib.auth.models import Group
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from . import models
from django.forms.widgets import NumberInput

class DateInput(forms.DateInput):
    input_type = 'date'

class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = models.MyUser
        fields = ('email', 'date_of_birth') 
        widgets = {
            'date_of_birth' : DateInput()
        }


    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = models.MyUser
        fields = ('email', 'password', 'date_of_birth', 'is_active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class UserAdmin(BaseUserAdmin):
    # The forms to add and change user instances
    form = UserChangeForm
    add_form = UserCreationForm

    # The fields to be used in displaying the User model.
    # These override the definitions on the base UserAdmin
    # that reference specific fields on auth.User.
    list_display = ('email', 'date_of_birth', 'is_admin')
    list_filter = ('is_admin',)
    fieldsets = (
        (None, {'fields': ('email', 'password')}),
        ('Personal info', {'fields': ('date_of_birth',)}),
        ('Permissions', {'fields': ('is_admin',)}),
    )
    # add_fieldsets is not a standard ModelAdmin attribute. UserAdmin
    # overrides get_fieldsets to use this attribute when creating a user.
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': ('email', 'date_of_birth', 'password1', 'password2'),
        }),
    )
    search_fields = ('email',)
    ordering = ('email',)
    filter_horizontal = ()


# Now register the new UserAdmin...
admin.site.register(models.MyUser, UserAdmin)
# ... and, since we're not using Django's built-in permissions,
# unregister the Group model from admin.
admin.site.unregister(Group)

django_app/ARTICLE_SUMMARY2/accounts/views.py
# accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseBadRequest
from django.views.decorators.http import (
    require_http_methods,
    require_safe,
    require_POST,
)
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib import auth
from .forms import UserCreationForm

User = get_user_model()


# Create your views here.
@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('board:index')
    else:
        form = UserCreationForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return HttpResponseBadRequest('이미 로그인 하였습니다.')

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('board:index')
    else:
        form = AuthenticationForm()
    context = {'form': form}
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('board:index')

django_app/ARTICLE_SUMMARY2/accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
	<title>Bootstrap Sign up Form Horizontal</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>

	<!-- Template Stylesheet -->
	<link href="{% static 'css/style.css' %}" rel="stylesheet">

	<style>
		body {
			color: #999;
			background: #f3f3f3;
			font-family: 'Roboto', sans-serif;
		}
		.form-control {
			border-color: #eee;
			min-height: 41px;
			box-shadow: none !important;
		}
		.form-control:focus {
			border-color: #a3abda;
		}
		.form-control, .btn {        
			border-radius: 3px;
		}
		.signup-form {
			width: 500px;
			margin: 0 auto;
			padding: 30px 0;
		}
		.signup-form h2 {
			color: #333;
			margin: 0 0 30px 0;
			display: inline-block;
			padding: 0 30px 10px 0;
			border-bottom: 3px solid #8F12FD;
		}
		.signup-form form {
			color: #999;
			border-radius: 3px;
			margin-bottom: 15px;
			background: #fff;
			box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
			padding: 30px;
		}
		.signup-form .form-group row {
			margin-bottom: 20px;
		}
		.signup-form label {
			font-weight: normal;
			font-size: 14px;
			line-height: 2;
		}
		.signup-form input[type="checkbox"] {
			position: relative;
			top: 1px;
		}
		.signup-form .btn {        
			font-size: 16px;
			font-weight: bold;
			background: #8F12FD;
			border: none;
			margin-top: 20px;
			min-width: 140px;
		}
		.signup-form .btn:hover, .signup-form .btn:focus {
			background: #8F12FD;
			outline: none !important;
		}
		.signup-form a {
			color: #8F12FD;
			text-decoration: underline;
		}
		.signup-form a:hover {
			text-decoration: none;
		}
		.signup-form form a {
			color: #8F12FD;
			text-decoration: none;
		}	
		.signup-form form a:hover {
			text-decoration: underline;
		}

		. {
			transition: .5s;
		}
	
		{% comment %} Button {% endcomment %}

		.btn.btn-primary-gradient,
		.btn.btn-secondary-gradient::after {
			background: linear-gradient(to bottom right, var(--primary), var(--secondary));
		}

	</style>
</head>
<body style="height: 1000px; margin:100px 0px"> 
	<div class="signup-form">
	{#    <form action="" method="post" class="form-horizontal">#}
	{#      	<div class="row">#}
	{#        	<div class="col-8 offset-4">#}
	{#				<h2>이메일로 로그인</h2>#}
	{#			</div>	#}
	{#      	</div>			#}
	{#		<div class="form-group row">#}
	{#			<label class="col-form-label col-4">이메일</label>#}
	{#			<div class="col-8">#}
	{#                <input type="email" class="form-control" name="email" required="required">#}
	{#            </div>        	#}
	{#        </div>#}
	{#		<div class="form-group row">#}
	{#			<label class="col-form-label col-4">비밀번호</label>#}
	{#			<div class="col-8">#}
	{#                <input type="password" class="form-control" name="password" required="required">#}
	{#            </div>        	#}
	{#        </div>#}
	{#    #}
	{#        <div class="form-group row">#}
	{#			<div class="col-8 offset-4">#}
	{#				{% csrf_token %}#}
	{#				<button type="submit" class="btn btn-primary btn-lg">로그인</button>#}
	{#			</div>  #}
	{#		</div>#}

		<form method="post" action="" class="form-horizontal" style="font-family: 'Poppins';">	
			<div class="row">
				<div class="col-8 offset-4">
					<h2 style="font-family: 'Poppins';">&nbsp;&nbsp;&nbsp;Log In</h2>
				</div>	
			</div>	
			<input type="hidden" name="csrfmiddlewaretoken" value="AEfw5WxwoN77Yqvcv63gqPIegEuW7CyqnCNgyspxby9VR1tcGyQruCVU9xgMMAzS">
			
			<div class="form-group row">
				<label for="id_username">email address:</label> 
				<div class="col-8">
					<input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="255" required="" id="id_username" class="form-control">

				</div>
			</div>
			<div class="form-group row">
				<label for="id_password">password: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </label> 
				<div class="col-8">
					<input type="password" name="password" autocomplete="current-password" required="" id="id_password" class="form-control">
				</div>
			</div>
			{% csrf_token %}
			<input type="submit" value="Log In" style="margin:auto;" class="btn btn-primary-gradient rounded-pill py-2 px-4 ms-3 d-none d-lg-block">
		</form>
		<div class="text-center" style="font-family: 'Poppins';" >Not a member yet? <a href="/accounts/signup/">Sign Up here</a></div>

	<!--
	<body style="height: 1000px; margin:100px 0px">
		<form method="post" action="" class="form-horizontal">	
			<div class="row">
				<div class="col-8 offset-4">
					<h2>로그인</h2>
				</div>	
			</div>	
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="로그인" style="display:block; background: #4AC4F3; margin:auto;" class="btn btn-primary btn-lg"/>
		</form>
		<div class="text-center">아직 회원이 아니신가요? <a href="{% url 'accounts:signup' %}">회원 가입</a></div>
	</body>
	-->
	</div>
</body>
</html>

django_app/ARTICLE_SUMMARY2/accounts/templates/accounts/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
<title>Bootstrap Sign up Form Horizontal</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

<!-- Template Stylesheet -->
<link href="{% static 'css/style.css' %}" rel="stylesheet">


<style>

	
body {
	color: #999;
	background: #f3f3f3;
	font-family: 'Roboto', sans-serif;
}
.form-control {
	border-color: #eee;
	min-height: 41px;
	box-shadow: none !important;
}
.form-control:focus {
	border-color: #a3abda;
}
.form-control, .btn {        
	border-radius: 3px;
}
.signup-form {
	width: 500px;
	margin: 0 auto;
	padding: 30px 0;
}
.signup-form h2 {
	color: #333;
	margin: 0 0 30px 0;
	display: inline-block;
	padding: 0 30px 10px 0;
	border-bottom: 3px solid #8F12FD;
}
.signup-form form {
	color: #999;
	border-radius: 3px;
	margin-bottom: 15px;
	background: #fff;
	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
	padding: 30px;
}
.signup-form .form-group row {
	margin-bottom: 20px;
}
.signup-form label {
	font-weight: normal;
	font-size: 14px;
	line-height: 2;
}
.signup-form input[type="checkbox"] {
	position: relative;
	top: 1px;
}
.signup-form .btn {        
	font-size: 16px;
	font-weight: bold;
	background: #8F12FD;
	border: none;
	margin-top: 20px;
	min-width: 140px;
}
.signup-form .btn:hover, .signup-form .btn:focus {
	background: #8F12FD;
	outline: none !important;
}
.signup-form a {
	color: #8F12FD;
	text-decoration: underline;
}
.signup-form a:hover {
	text-decoration: none;
}
.signup-form form a {
	color: #8F12FD;
	text-decoration: none;
}	
.signup-form form a:hover {
	text-decoration: underline;
}

		{% comment %} Button {% endcomment %}

		.btn.btn-primary-gradient,
		.btn.btn-secondary-gradient::after {
			background: linear-gradient(to bottom right, var(--primary), var(--secondary));
		}

</style>
</head>
<body style="height: 1000px; margin:100px 0px">
<div class="signup-form">

	<form method="post" action="" style="font-family: 'Poppins';">
		<div class="row ">
			<div class="col-8 offset-4">
				<h2 style="font-family: 'Poppins';">&nbsp;&nbsp;&nbsp;Sign Up</h2>
			</div>	
		</div>
		<input type="hidden" name="csrfmiddlewaretoken" value="GdY1grrN8NxA7qrK41BvDP2kmoOc9gZtQRneHupQw603srFhHdkPAwnSqbbEnJSg">

		<div class="form-group row">
			<label for="id_email">email address:</label> 
			<div class="col-8">
				<input type="email" name="email" maxlength="255" required="" id="id_email" class="form-control">
			</div>
		</div>
		
		<div class="form-group row">
			<label for="id_date_of_birth">Birth:</label> 
			<div class="col-8">
				<input type="date" name="date_of_birth" required="" id="id_date_of_birth" class="form-control">
			</div>
		</div>
		
		<div class="form-group row">
			<label for="id_password1">password:</label> 
			<div class="col-8">
				<input type="password" name="password1" required="" id="id_password1" class="form-control">
			</div>
		</div>
		
		<div class="form-group row">
			<label for="id_password2">Confirm Password:</label> 
			<div class="col-8">
				<input type="password" name="password2" required="" id="id_password2" class="form-control">
			</div>
		</div>
		{% csrf_token %}
		<input type="submit" value="Sign Up" style="margin:auto;" class="btn btn-primary-gradient rounded-pill py-2 px-4 ms-3 d-none d-lg-block">
	</form>
	<div class="text-center" style="font-family: 'Poppins';">Already have an account? <a href="/accounts/login/">Login here</a></div>
<!--
<body style="height: 1000px; margin:100px 0px">
	<form method="post" action="">
		<div class="row">
			<div class="col-8 offset-4">
				<h2>회원가입</h2>
			</div>	
		</div>
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="회원가입" style="display:block; background: #4AC4F3; margin:auto;" class="btn btn-primary btn-lg"/>
	</form>
	<div class="text-center" >이미 회원이신가요? <a href="{% url 'accounts:login' %}" >로그인 하기</a></div>
</body>
-->
</div>
</body>
</html>