django_app/ARTICLE_SUMMARY2/ARTICLE_SUMMARY2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('', lambda request : redirect('board/', permanent=False)), # permanent = True로 설정하면 영구적 인 리디렉션이 발행됩니다.
    path('accounts/', include('accounts.urls')),
]

django_app/ARTICLE_SUMMARY2/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('crawl/', views.text_summarizae_request_ajax, name='text_summarizae_request_ajax'),
    path('summarize/', views.news_summarizae_request_ajax, name='news_summarizae_request_ajax'),
    path('comments/', views.news_comments_request_ajax, name='news_comments_request_ajax'),
    path('history/', views.history_request_ajax, name='history_request_ajax'),
    
    # path('summarize/', views.summarize, name='summarize'),
]

django_app/ARTICLE_SUMMARY2/board/models.py
from django.db import models
from accounts.models import MyUser
# Create your models here.


class NewsArticleInfo(models.Model):
    title = models.CharField(max_length=100)
    detail = models.TextField()
    url = models.CharField(unique=True, max_length=200)
    press = models.CharField(max_length=100)
    journalist = models.CharField(max_length=20)
    summary = models.CharField(max_length=1000)
    article_date = models.DateTimeField()
    modify_date = models.DateTimeField(blank=True, null=True)
    section = models.CharField(max_length=30)

    class Meta:
        managed = False
        db_table = 'news_article_info'


class NewsArticleComments(models.Model):
    article_url = models.ForeignKey('NewsArticleInfo', models.DO_NOTHING, db_column='article_url')
    username = models.CharField(max_length=40)
    content = models.CharField(max_length=300, blank=True, null=True)
    sympathycount = models.IntegerField(db_column='sympathyCount')  # Field name made lowercase.
    antipathycount = models.IntegerField(db_column='antipathyCount')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'news_article_comments'


class UserSummarizationRequest(models.Model):
    id = models.IntegerField(primary_key=True)
    userid = models.ForeignKey(MyUser, models.DO_NOTHING, db_column='userid')
    url = models.ForeignKey(NewsArticleInfo, models.DO_NOTHING, db_column='url')
    request_time = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'user_summarization_request'

django_app/ARTICLE_SUMMARY2/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseForbidden
from django.views.decorators.http import (require_http_methods,
                                            require_safe, require_POST)

from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.http import JsonResponse
import json
from .newsCrawler import NewsCrawler
import requests
import re
from . import models
from django.db.models import Q
from django.conf import settings

# Create your views here.


@require_safe
def index(request):
    return render(request, 'board/index.html')


# @login_required
# @require_http_methods(['GET', 'POST'])
# def create(request):
#     if request.method == 'POST':
#         form = UserForm()
#         if form.is_valid():
#             article = form.save(commit=False)
#             article.username = request.username
#             article.save()
#             return redirect('board:detail', article.pk)
#     else:
#         form = UserForm()
#         context = {'form' : form}
#         return render(request, 'board/join_membership.html', context)


@require_http_methods(['POST'])
def news_summarizae_request_ajax(request):
    # print(request.body)
    url = json.loads(request.body)['url']
    url = url.replace('/mnews','')
    url = url.replace('/newspaper','')

    naver_url_regex = r'(http|https)://n.news.naver.com/article/\d+/\d+'
    regex = re.compile(naver_url_regex)
    url = regex.match(url)
    print(url)
    
    if not url:
        print('error 올바르지 않는 url')
        return JsonResponse({'status':'false', 'message': '잘못된 url'}, status=500)
    url = url[0]

    # DB에서 해당 url에 맞는 데이터 필드 가져옴.
    crawl_data_dict = NewsCrawler.navercrawl(url)
    news_article = models.NewsArticleInfo()
    request_body = {
        "text" : crawl_data_dict['text'].strip()

    }
    # print('test1 통과')
    # DB에 해당 URL로 있는것을 조회 
    # 입력받은 URL을 가진 기사가 데이터베이스에 존재하는지 확인.
    if models.NewsArticleInfo.objects.filter(url=url) :
        # 해당 URL을 가진 기사가 데이터베이스에 존재하면, 수정일자를 비교하여 최신 버전인지 확인.
        if (models.NewsArticleInfo.objects.filter(Q(url=url) & Q(modify_date__isnull=True)) and crawl_data_dict.get('modify_date') != -1 ) or models.NewsArticleInfo.objects.filter(Q(url=url) & Q(modify_date = crawl_data_dict.get('modify_date'))):
            news_article = models.NewsArticleInfo.objects.get(url=url)

            return JsonResponse(
                {
                    'summarize' : news_article.summary,
                    'title' : crawl_data_dict['title'],
                    'newspaper' : crawl_data_dict['press'],
                    'category' : crawl_data_dict['section'],
                    'date' : crawl_data_dict['write_date'],
                }
            )
        # 최신 버전이 아닐 경우, 기사의 내용을 업데이트하고 요약을 다시 생성.
        else:
            news_article = models.NewsArticleInfo.objects.get(url=url)
            news_article.detail = crawl_data_dict['text']
            news_article.modify_date = crawl_data_dict['modify_date']
            request_body = {
                "text" : crawl_data_dict['text']

            }
            request_body = json.dumps(request_body)
            r = requests.post('http://13.208.62.74:8908/summarize/text/', data=request_body)

            #정상적인 응답을 못 받았을때
            if r.status_code != 200 :
                return JsonResponse({'status': 'false', 'message': 'fastapi가 응답 없음'}, status=500)
            json_data = r.json()['message'][0].get('summary_text').strip()
            news_article.summary = json_data
            news_article.update()
            return JsonResponse(
                {
                    'summarize' : json_data,
                    'title' : crawl_data_dict['title'],
                    'newspaper' : crawl_data_dict['press'],
                    'category' : crawl_data_dict['section'],
                    'date' : crawl_data_dict['write_date'],
                
                }
            )



    # DB 모델 객체의 값 채움
    news_article.title = crawl_data_dict['title']
    news_article.detail = crawl_data_dict['text']
    news_article.url = url
    news_article.press = crawl_data_dict['press']
    news_article.journalist = crawl_data_dict['reporter']
    news_article.section = crawl_data_dict['section']
    news_article.article_date = crawl_data_dict['write_date']
    if crawl_data_dict['modify_date'] != -1:
        news_article.modify_date = crawl_data_dict['modify_date']
    else :
        pass
    request_body = json.dumps(request_body)
    print(len(crawl_data_dict['text']))
    request_summarize = requests.post('http://13.208.62.74:8908/summarize/text/', data=request_body)
    if request_summarize.status_code != 200:
        pass
    json_data = request_summarize.json()['message'][0].get('summary_text').strip()
    news_article.summary = json_data
    # 모델저장 
    news_article.save()

    print(json_data)
    return JsonResponse(
        {
            'title' : crawl_data_dict['title'],
            'newspaper' : crawl_data_dict['press'],
            'category' : crawl_data_dict['section'],
            'summarize' : json_data,          
            'date' : crawl_data_dict['write_date'], 
        }
    )
    

@require_http_methods(['POST'])
def news_comments_request_ajax(request):

    url = json.loads(request.body)['url']
    url = url.replace('/mnews','')
    url = url.replace('/newspaper','')
    naver_url_regex = r'(http|https)://n.news.naver.com/article/\d+/\d+'
    regex = re.compile(naver_url_regex)
    url = regex.match(url)
    print(f'\n 최종 url : {url}\n')
    
    if not url :
        print('error 올바르지 않는 url')
    url = url[0]

    comments_object = models.NewsArticleComments()
    crawl_comment_list = NewsCrawler.get_news_comment(url=url)

    # comments가 0 인지 확인
    if crawl_comment_list == [] :
        return JsonResponse({'comments': []})



    r = requests.post('http://13.208.62.74:8908/emotion/text/', data=json.dumps({'comments': crawl_comment_list}))
    json_data = r.json()




    # 프론트 엔드 테스트 할 수 있는 코드
    # for i in range(len(crawl_comment_list)) :
    #     crawl_comment_list[i]['emotion'] = random.randrange(0, 2)
    #     crawl_comment_list[i]['emotion_value'] = random.random()

    return JsonResponse(json_data)



def history_request_ajax(request):
    return render(request, 'board/history.html')

django_app/ARTICLE_SUMMARY2/board/templates/board/detail.html
{% extends 'base.html' %}

django_app/ARTICLE_SUMMARY2/board/templates/board/history.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>ShortZip - Summarize your news articles!</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/animate/animate.min.css" rel="stylesheet">
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<div class="container-xxl bg-white p-0">
    <!-- Spinner Start -->
    <div id="spinner"
         class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-grow text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar & Hero Start -->
    <div class="container-xxl position-relative p-0" data-wow-delay="0.01s" id="home">
        <div class="container-xxl bg-primary hero-header" style="height: 750px">
            <div class="container">
                <div class="row g-5 align-items-center" style="justify-content: center;height:200px">
                    <div class="col-lg-6 text-center text-lg-start" style="color:#FFFFFF; width:70%">
                        <h3 class="text-white mb-4 animated slideInDown"
                            style="text-align:center;font-family: 'Poppins', sans-serif;">Preparing the service. Please be patient.</h3>
                        <h3 class="text-white mb-4 animated slideInDown"
                        style="text-align:center;font-family: 'Poppins', sans-serif;">Back to Home!</h3>
                        <div class="overflow-hidden">
                            <div data-zanim-xs="{&quot;delay&quot;:0.2}" style="text-align:center">
                                <a class="display:block" style="color:#FFFFFF;font-family: 'Poppins', sans-serif;text-align:center"
                                   href="{% url 'board:index' %}">Click ⟶
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Navbar & Hero End -->



    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>